specfile_path: packaging/fedora/aura-code.spec
files_to_sync:
  - packaging/fedora/aura-code.spec
  - .packit.yaml

upstream_package_name: aura-code
downstream_package_name: aura-code

srpm_build_deps:
  - npm

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-44-x86_64
      - fedora-rawhide-x86_64

  - job: copr_build
    trigger: commit
    branch: master
    targets:
      - fedora-44-x86_64
      - fedora-rawhide-x86_64

  - job: copr_build
    trigger: release
    targets:
      - fedora-44-x86_64
      - fedora-rawhide-x86_64
