/**
 * The theme layer: the two adOS file formats, the token fill-out that makes a
 * seven-colour theme legible in a terminal, and the resolution order that
 * decides which palette the TUI wears.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  THEME_TOKENS, allThemes, auraThemeFile, configuredThemeId, currentTheme,
  DEFAULT_THEME_ID, expandTokens, mixHex, onThemeChange, parseThemeFile,
  reloadThemes, resetThemeState, saveThemeChoice, setTheme, adOSThemeId, themeById,
  reloadThemes, resetThemeState, saveThemeChoice, setTheme, themeById,
} from '../src/cli/theme.js';
import { handleThemeCommand } from '../src/cli/repl-theme-commands.js';

/** The generated form: `~/.config/aura/themes/<name>.conf`. */
const CONF = [
  '# generated by aura-os-theme',
  'NAME="Gruvbox"',
  'BG="#1d2021"',
  'SURFACE="#282828"',
  'LINE="#3c3836"',
  'FG="#ebdbb2"',
  'DIM="#665c54"',
  'ACCENT="#fe8019"',
  'ACCENT2="#fabd2f"',
  'FONT="JetBrainsMono Nerd Font, monospace"',
  'RADIUS="0px"',
].join('\n');

/** The source form: `<aura-os>/themes/<name>/palette`. */
const PALETTE = [
  '# tokyo-night — cool blue on deep navy',
  'bg=#1a1b26',
  'bg_alt=#1f2335',
  'border=#292e42',
  'fg=#c0caf5',
  'fg_bright=#e0e6ff',
  'dim=#565f89',
  'muted=#737aa2',
  'accent=#7aa2f7',
  'accent_bright=#89b4fa',
  'red=#f7768e',
  'green=#9ece6a',
  'yellow=#e0af68',
  'blue=#7aa2f7',
  'cyan=#7dcfff',
  'orange=#ff9e64',
].join('\n');

let tmp: string;
let realHome: string | undefined;

beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'aura-theme-'));
  realHome = process.env.HOME;
  delete process.env.AURA_THEME;
  delete process.env.AURA_THEME_DIR;
  delete process.env.AURA_OS_DIR;
  // Never write the real ~/.aura/theme from a test.
  process.env.AURA_THEME_FILE = path.join(tmp, 'theme');
  resetThemeState();
});

afterEach(() => {
  if (realHome) process.env.HOME = realHome;
  delete process.env.AURA_THEME;
  delete process.env.AURA_THEME_DIR;
  delete process.env.AURA_OS_DIR;
  delete process.env.AURA_THEME_FILE;
  resetThemeState();
  fs.rmSync(tmp, { recursive: true, force: true });
});

describe('the adOS theme file formats', () => {
  it('parses the generated .conf, quotes and all', () => {
    const parsed = parseThemeFile(CONF);
    expect(parsed.name).toBe('Gruvbox');
    expect(parsed.font).toBe('JetBrainsMono Nerd Font, monospace');
    expect(parsed.radius).toBe('0px');
    expect(parsed.tokens).toMatchObject({
      bg: '#1d2021', bgAlt: '#282828', line: '#3c3836',
      fg: '#ebdbb2', dim: '#665c54', chrome: '#fe8019', accent2: '#fabd2f',
    });
  });

  it('parses the lowercase palette, keeping the # of a colour', () => {
    const parsed = parseThemeFile(PALETTE);
    expect(parsed.tokens).toMatchObject({
      bg: '#1a1b26', bgAlt: '#1f2335', line: '#292e42', fg: '#c0caf5',
      dim: '#565f89', chrome: '#7aa2f7', accent2: '#89b4fa',
      ok: '#9ece6a', warn: '#e0af68', err: '#f7768e', cyan: '#7dcfff',
    });
  });
});

describe('token fill-out', () => {
  it('gives a seven-colour theme every slot the TUI paints with', () => {
    const full = expandTokens({ bg: '#101010', fg: '#f0f0f0', chrome: '#ff8800' })!;
    for (const token of THEME_TOKENS) {
      expect(full[token], token).toMatch(/^#[0-9a-f]{6}$/i);
    }
    expect(full.chrome).toBe('#ff8800');
    expect(full.accent).toBe('#ff8800');
    expect(full.dim).not.toBe(full.fg);
  });

  it('refuses a palette with no background', () => {
    expect(expandTokens({ fg: '#ffffff' })).toBeNull();
  });

  it('mixes two colours', () => {
    expect(mixHex('#000000', '#ffffff', 0.5)).toBe('#808080');
  });
});

describe('the installed themes', () => {
  it('ships the themes adOS ships, plus the TUI default', () => {
    const themes = allThemes();
    const ids = themes.map(t => t.id);
    for (const id of [DEFAULT_THEME_ID, 'gruvbox', 'nord', 'tokyo-night', 'paper', 'mono', 'purplerain']) {
      expect(ids, id).toContain(id);
    }
    for (const t of themes) {
      for (const token of THEME_TOKENS) expect(t.tokens[token], `${t.id}.${token}`).toMatch(/^#[0-9a-f]{6}$/i);
      expect(t.gradient).toHaveLength(4);
    }
  });

  it('reads a theme off disk and lets it replace the built-in', () => {
    const dir = path.join(tmp, 'os', 'themes');
    fs.mkdirSync(path.join(dir, 'acme'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'acme', 'palette'), 'bg=#123456\nfg=#eeeeee\naccent=#00ffcc\n');
    fs.mkdirSync(path.join(dir, 'gruvbox'), { recursive: true });
    fs.writeFileSync(path.join(dir, 'gruvbox', 'palette'), 'bg=#000000\nfg=#ffffff\n');
    process.env.AURA_OS_DIR = path.join(tmp, 'os');
    // Sandbox $HOME too: the host's real ~/.config/aura/themes outranks the
    // OS dir and would leak machine state into this test.
    process.env.HOME = tmp;
    reloadThemes();

    const acme = themeById('acme');
    expect(acme?.tokens.bg).toBe('#123456');
    expect(acme?.tokens.chrome).toBe('#00ffcc');
    expect(acme?.name).toBe('Acme');
    expect(themeById('gruvbox')?.tokens.bg).toBe('#000000');
  });
});

describe('the active theme', () => {
  it('wears the TUI default until told otherwise', () => {
    expect(currentTheme().id).toBe(DEFAULT_THEME_ID);
  });

  it('resolves $AURA_THEME over the saved choice', () => {
    saveThemeChoice('mono');
    process.env.AURA_THEME = 'nord';
    resetThemeState();
    expect(currentTheme().id).toBe('nord');
  });

  it('switches live and notifies the repaint listener', () => {
    const seen: string[] = [];
    onThemeChange(t => seen.push(t.id));
    const next = setTheme('tokyo-night');
    expect(next?.id).toBe('tokyo-night');
    expect(currentTheme().id).toBe('tokyo-night');
    expect(seen).toEqual(['tokyo-night']);
  });

  it('refuses an unknown theme and keeps the current one', () => {
    expect(setTheme('nope')).toBeNull();
    expect(currentTheme().id).toBe(DEFAULT_THEME_ID);
  });

  it('persists the choice to ~/.aura/theme', () => {
    saveThemeChoice('gruvbox');
    expect(fs.readFileSync(auraThemeFile(), 'utf8')).toBe('gruvbox\n');
    expect(configuredThemeId()).toBe('gruvbox');
  });

  it('can read the theme adOS itself is wearing', () => {
    fs.mkdirSync(path.join(tmp, '.config', 'aura'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.config', 'aura', 'theme'), 'purplerain\n');
    const realHome = process.env.HOME;
    process.env.HOME = tmp;
    try {
      expect(adOSThemeId()).toBe('purplerain');
    } finally {
      process.env.HOME = realHome;
    }
  });
});

describe('the :theme command', () => {
  it('wears a named theme and remembers it', () => {
    expect(handleThemeCommand(':theme nord')).toEqual({ handled: true });
    expect(currentTheme().id).toBe('nord');
    expect(fs.readFileSync(auraThemeFile(), 'utf8')).toBe('nord\n');
  });

  it('lists and ignores what it cannot wear', () => {
    expect(handleThemeCommand(':theme')).toEqual({ handled: true });
    expect(handleThemeCommand(':theme nope')).toEqual({ handled: true });
    expect(handleThemeCommand(':syntax-highlight off')).toBeNull(); // not ours
    expect(currentTheme().id).toBe(DEFAULT_THEME_ID);
  });

  it('syncs to whatever adOS is wearing', () => {
    fs.mkdirSync(path.join(tmp, '.config', 'aura'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.config', 'aura', 'theme'), 'mono\n');
    const realHome = process.env.HOME;
    process.env.HOME = tmp;
    try {
      expect(handleThemeCommand(':theme sync')).toEqual({ handled: true });
      expect(currentTheme().id).toBe('mono');
    } finally {
      process.env.HOME = realHome;
    }
  });

  it('resets to the default', () => {
    handleThemeCommand(':theme tokyo-night');
    handleThemeCommand(':theme reset');
    expect(currentTheme().id).toBe(DEFAULT_THEME_ID);
  });
});
