/**
 * Single source of truth for the ":help" text — the REPL's `:help` command
 * prints HELP_TEXT verbatim. (The TUI sidebar used to derive a quick-command
 * list from this file too; that panel section was removed by design — the
 * command list lives in :help, not permanently on screen.)
 */

export const HELP_TEXT = [
  '',
  '  ── Session ──────────────────────────────────────',
  '  :id                     Show current chat ID',
  '  :sessions               List all saved sessions',
  '  :resume                 Resume the latest session',
  '  :resume <id>            Resume a specific session by ID',
  '  :new                    Start a new session (fresh history)',
  '  :history                Show turn count in current session',
  '  :clear-history          Wipe conversation history (keep session ID)',
  '  :save [title]           Rename / save current session',
  '  :delete <id>            Delete a saved session',
  '',
  '  ── Model / API ──────────────────────────────────',
  '  :model                  Interactive model selector',
  '  :model <id>             Switch to a specific model',
  '  :provider               Pick provider, then model (live-fetched lists)',
  '  :apikey <key>           Set API key for current session',
  '',
  '  ── Workflows ─────────────────────────────────────',
  '  :workflows              List all saved workflows',
  '  :workflow               Create & run a multi-step workflow',
  '    <name> "step1" "step2" ...',
  '  :resume-workflow <id>   Resume a paused/failed workflow',
  '  :q add <prompt>         Enqueue a task in the queue',
  '  :q list                 List queued tasks',
  '  :q run <n>              Execute queued task #n',
  '  :q drop <n>             Remove queued task #n',
  '  :q clear                Wipe the queue',
  '  :machina <task>         Run task with self-verification + auto-retry',
  '  :council <task>         2-3 parallel read-only specialists, then synthesis',
  '  :ecclesia <topic>       5 independent research agents + synthesis verdict',
  '    [--panel <model>] [--seats <n>]   (saved to council/*.md|.html)',
  '',
  '  ── Memory / Side ─────────────────────────────────',
  '  :dream                  Consolidate recent episodes into a dream entry',
  '  :dream full             Consolidate ALL episodes, ignoring last-dream cutoff',
  '  :rem                    Show reconciled memory (or latest dream)',
  '  :mine                   Mine episodes for patterns (zero-LLM clustering)',
  '  :mine --refine          Also judge concepts locally -> training-data/*.jsonl',
  '  :research <topic>       Multi-step research pass, saved to research/*.md',
  '  :confess                Auto-detect & confess an anomalous episode',
  '  :confessions            List all confessions',
  '  :btw <question>         Quick side question (read-only, no history pollution)',
  '',
  '  ── Voice ─────────────────────────────────────────',
  '  :speak                  Toggle reading replies aloud (or launch with --speak)',
  '',
  '  ── Safety ────────────────────────────────────────',
  '  :approve                Toggle auto-approve (skip per-command y/N prompts)',
  '  :approve all            Approve everything this session',
  '  :approve off            Re-enable confirmation for destructive commands',
  '',
  '  ── Ruby ──────────────────────────────────────────',
  '  :rubyon                 Enable Ruby Alternator for this session (overrides .aura.json)',
  '  :rubyoff                Disable Ruby Alternator for this session (overrides .aura.json)',
  '  :rubymodel <tag>        Set Ruby local model for this session (e.g. :rubymodel qwen3-vl:4b)',
  '  :rubymodel              Show current Ruby model setting',
  '',
  '  ── Context / Stats ──────────────────────────────',
  '  :compact, :compress     Force compaction now (reuses auto-compaction logic)',
  '  :context                Show loaded project context',
  '  :graph                  Show codebase knowledge graph summary',
  '  :graph refresh          Reload graph from graphify-out/graph.json',
  '  :plans                  List saved execution plans',
  '  :viz, :dashboard        Generate and open the memory dashboard',
  '  :doctor                 Scan Aura itself for issues (build, config, deps, env)',
  '  :doctor --fix           Scan and attempt auto-repairs',
  '  /stats, /usage          Show token + cost usage this session',
  '  /context                Context health dashboard (window, compaction, cost)',
  '  /clear, /reset          Reset cumulative usage stats',
  '',
  '  ── General ──────────────────────────────────────',
  '  :quit, :q, /exit        Exit',
  '',
];

