/**
 * Single source of truth for the ":help" text — the REPL's `:help` command
 * prints HELP_TEXT verbatim. (The TUI sidebar used to derive a quick-command
 * list from this file too; that panel section was removed by design — the
 * command list lives in :help, not permanently on screen.)
 */

export const HELP_TEXT = [
  '',
  '  ── Modes ────────────────────────────────────────',
  '  :coder                  Switch to full coding-agent mode (tools, project context)',
  '  :gazelle                Switch to lean conversational mode',
  '',
  '  ── Session ──────────────────────────────────────',
  '  :id                     Show current chat ID',
  '  :sessions               List all saved sessions',
  '  :resume                 Resume the latest session',
  '  :resume <id>            Resume a specific session by ID',
  '  :new                    Start a new session (fresh history)',
  '  :history                Show turn count in current session',
  '  :clear-history          Wipe conversation history (keep session ID)',
  '  :save [title]           Rename / save current session',
  '  :delete <id>            Delete a saved session',
  '',
  '  ── Model / API ──────────────────────────────────',
  '  :model                  Interactive model selector',
  '  :model <id>             Switch to a specific model',
  '  :provider               Pick provider, then model (live-fetched lists)',
  '  :apikey <key>           Set API key for current session',
  '',
  '  ── Skills ───────────────────────────────────────',
  '  :skills                 List skills the agent can route to',
  '  :skills <query>         Filter that list by name or description',
  '',
  '  ── Workflows ─────────────────────────────────────',
  '  :workflows              List all saved workflows',
  '  :workflow               Create & run a multi-step workflow',
  '    <name> "step1" "step2" ...',
  '  :resume-workflow <id>   Resume a paused/failed workflow',
  '  :q add <prompt>         Enqueue a task in the queue',
  '  :q list                 List queued tasks',
  '  :q run <n>              Execute queued task #n',
  '  :q drop <n>             Remove queued task #n',
  '  :q clear                Wipe the queue',
  '  :machina <task>         Run task with self-verification + auto-retry',
  '  :council <task>         2-3 parallel read-only specialists, then synthesis',
  '  :ecclesia <topic>       5 independent research agents + synthesis verdict',
  '    [--panel <model>] [--seats <n>]   (saved to council/*.md|.html)',
  '',
  '  ── Memory / Side ─────────────────────────────────',
  '  :dream                  Consolidate recent episodes into a dream entry',
  '  :dream full             Consolidate ALL episodes, ignoring last-dream cutoff',
  '  :rem                    Show reconciled memory (or latest dream)',
  '  :mine [--refine]        Mine episodes for patterns; --refine judges concepts with the local model',
  '  :mine --corrections    Write direct correction pairs from escalation episodes (Path B)',
  '  :mine --stats          Show training-data row counts by provenance',
  '  :mine --refine          Also judge concepts locally -> training-data/*.jsonl',
  '  :research <topic>       Multi-step research pass, saved to research/*.md',
  '  :confess                Auto-detect & confess an anomalous episode',
  '  :confessions            List all confessions',
  '  :btw <question>         Quick side question (read-only, no history pollution)',
  '',
  '  ── What Aura has learned ─────────────────────────',
  '  :lessons                Everything learned, both scopes, with keys',
  '  :lessons global|project Only that scope',
  '  :lessons timeline       When things were learned, as a per-day chart',
  '  :lessons <text>         Only lessons matching that text',
  '  :forget <key>           Remove one lesson from the prompt for good',
  '',
  '  ── Catch a job and repeat it ─────────────────────',
  '  :catchthis [name]       Start recording what you do; type it again to stop',
  '  :catchthis list         Everything caught so far',
  '  :catchthis show <id>    The steps it saw',
  '  :catchthis run <id> [n] Hand it to the agent, optionally n times',
  '  :catchthis forget <id>  Delete a recording',
  '',
  '  ── The web client ────────────────────────────────',
  '  :auraweb                Start the browser client and open it',
  '  :auraweb --port 8080    Serve it somewhere else',
  '                          (`webaura` does the same from a plain terminal)',
  '',
  '  ── Computer use (screen + mouse + keyboard) ──────',
  '  :compon                 Turn computer use ON (shows the disclosure first)',
  '  :compoff                Turn it OFF and release the input device',
  '  :comp                   Show whether it is on, and what is holding it there',
  '',
  '  ── While a task is running ───────────────────────',
  '  <anything else>         Steers the running task — folded in at the next turn,',
  '                          without restarting it or losing the work so far',
  '  :stop  /  :cancel       Abort the running task',
  '  ── Design ────────────────────────────────────────',
  '  :designx <brief>        Design commission: routes a style direction, scrapes real',
  '                          references, then builds the artefact into design/*',
  '  :designx web|deck|pdf <brief>   Force the artefact type (otherwise inferred)',
  '    [--classic|--wild|--feral]    How far off convention to push (default: balanced)',
  '    [--style <id>] [--seed <n>] [--count <n>] [--no-scrape] [--out <dir>]',
  '  :designx styles         List the design lexicon',
  '',
  '  ── Voice ─────────────────────────────────────────',
  '  :speak                  Toggle reading replies aloud (or launch with --speak)',
  '',
  '  ── Safety ────────────────────────────────────────',
  '  :approve                Toggle auto-approve (skip per-command y/N prompts)',
  '  :approve all            Approve everything this session',
  '  :approve off            Re-enable confirmation for destructive commands',
  '',
  '  ── Turn Limit ────────────────────────────────────',
  '  :turnsoff               Turn off loop turn limit (unlimited turns per task)',
  '  :turnson                Turn on loop turn limit (restore 50-turn cap)',
  '  :turns [n|off|on]       Show or set turn limit for this session',
  '',
  '  ── Archimedes ──────────────────────────────────────────',
  '  :archon                 Enable Archimedes Alternator for this session (overrides .aura.json)',
  '  :archoff                Disable Archimedes Alternator for this session (overrides .aura.json)',
  '  :archmodel <tag>        Set Archimedes local model for this session (e.g. :archmodel qwen3-vl:4b)',
  '  :archmodel              Show current Archimedes model setting',
  '  :small1                 Force tasks to START with Archimedes this session (bypasses competence gate;',
  '                          verification/escalation still run, score updates normally)',
  '  :small1 off             Revert to normal competence-gated routing',
  '  :cost                   Cost ledger: spent vs direct-large counterfactual, per outcome',
  '                          (reads ~/.aura/cost-log/*.jsonl — one row per Archimedes attempt)',
  '',
  '  ── Context / Stats ──────────────────────────────',
  '  :compact, :compress     Force compaction now (reuses auto-compaction logic)',
  '  :context                Show loaded project context',
  '  :graph                  Show codebase knowledge graph summary',
  '  :graph refresh          Reload graph from graphify-out/graph.json',
  '  :plans                  List saved execution plans',
  '  :viz, :dashboard        Generate and open the memory dashboard',
  '  :doctor                 Scan Aura itself for issues (build, config, deps, env)',
  '  :doctor --fix           Scan and attempt auto-repairs',
  '  /stats, /usage          Show token + cost usage this session',
  '  /cost [n]               Cache hit rate + cost per call (default last 20)',
  '  /context                Context health dashboard (window, compaction, cost)',
  '  /context tune, /ct      Adjust when compaction fires (←/→ on the ladder)',
  '  /clear, /reset          Reset cumulative usage stats (history unchanged — see :new)',
  '',
  '  ── General ──────────────────────────────────────',
  '  :quit, :q, /exit        Exit',
  '',
];

